length_in_x: 4.0
length_in_y: 4.0
position_x: 0.0
position_y: 0.0
resolution: 0.025
min_variance: 0.001
max_variance: 10.0
mahalanobis_distance_threshold: 2.0
multi_height_noise: 0.01
surface_normal_estimation_radius: 0.20
surface_normal_positive_axis: z
