# For the Zed Camera, a WIP
sensor_processor/type: Stereo

#These don't seem to exist for the ZED... Will ask on forums.
sensor_processor/p_1: 0.0
sensor_processor/p_2: 0.0
sensor_processor/p_3: 0.0
sensor_processor/p_4: 0.0
sensor_processor/p_5: 0.0

#This seems to be a constant error per distance. eg 0.001m error per meter of measurement LATTERALLY. Testing made up values atm
sensor_processor/lateral_factor: 0.05

# This should be focal length * baseline. Units? For ZED VGA: 350.04*0.12
sensor_processor/depth_to_disparity_factor: 42.0048
sensor_processor/cutoff_min_depth: 0.8
sensor_processor/cutoff_max_depth: 5.0
